sudo: required
language: node_js
node_js: stable
cache: yarn
dist: trusty
addons:
  ssh_known_hosts: "$DEPLOY_HOST"
before_script:
  - npm install pm2 -g
before_install:
  - openssl aes-256-cbc -K $encrypted_531226d110e9_key -iv $encrypted_531226d110e9_iv -in deploy_rsa.enc -out deploy_rsa -d
  - pwd
  - ls -la
after_install:
  - yarn test
before_deploy:
  - echo -e "Host deploy\n\tHostName $DEPLOY_HOST\n\tIdentityFile /tmp/deploy_rsa\n\tUser
    $DEPLOY_USER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
install:
  - npm install --save
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r $TRAVIS_BUILD_DIR/build/* $DEPLOY_USER@deploy:lyra-graphql/lib/
    - pm2 restart index
  on:
    branch: master
