sudo: required
dist: trusty

stages:
  - tests
  - name: deploy_prod
    if: branch = master
  - name: deploy_test
    if: branch = staging

services:
  - docker
before_install:
  - docker --version
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - docker --version
  - docker build --tag=elasticsearchtest .
  - docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearchtest
  - docker container ls
  - sleep 30
  - curl http://0.0.0.0:9200

jobs:
  include:
    - stage: tests
      language: python
      python: "2.7"
      install:
        - cd loader
        - pip install -r pip-requires.txt
        - pip install --upgrade pytest
      script:
        - pwd
        - python -m pytest test -v -s
    - stage: tests
      language: node_js
      node_js: stable
      cache: yarn
      install:
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - pip install virtualenv
        - virtualenv ~/pythonenv
        - source ~/pythonenv/bin/activate
        - cd loader
        - pip install -r ./pip-requires.txt
        - python tree_cellscape/tree_cellscape_loader.py -y ../example/analysis_yaml.yaml
      script:
        - pwd
        - cd ..
        - npm install --save
        - npm run test
    - stage: deploy_prod
      language: node_js
      node_js: stable
      cache: yarn
      addons:
        ssh_known_hosts: "$DEPLOY_HOST"
      before_install:
        - openssl aes-256-cbc -K $encrypted_531226d110e9_key -iv $encrypted_531226d110e9_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - pwd
        - ls -la
      before_deploy:
        - echo -e "Host deploy\n\tHostName $DEPLOY_HOST\n\tIdentityFile /tmp/deploy_rsa\n\tUser
          $DEPLOY_USER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - ssh $DEPLOY_USER@deploy 'bash updateServer.sh'
    - stage: deploy_test
      language: node_js
      node_js: stable
      cache: yarn
      addons:
        ssh_known_hosts: "$DEPLOY_TEST_HOST"
      before_install:
        - openssl aes-256-cbc -K $encrypted_531226d110e9_key -iv $encrypted_531226d110e9_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - pwd
        - sudo apt-get install apt-transport-https lsb-release software-properties-common dirmngr -y
        - AZ_REPO=$(lsb_release -cs)
        - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
          sudo tee /etc/apt/sources.list.d/azure-cli.list
        - sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv \
          --keyserver packages.microsoft.com \
          --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
        - sudo apt-get update
        - sudo apt-get install azure-cli
        - ls -la
      before_deploy:
        - echo -e "Host deploy\n\tHostName $DEPLOY_TEST_HOST\n\tIdentityFile /tmp/deploy_rsa\n\tUser
          $DEPLOY_USER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      script:
        - pwd
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - ssh $DEPLOY_USER@deploy 'bash updateServer.sh'
        on:
          branch: staging
