version: "3"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./loader/Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
  graphql:
    container_name: graphql
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "4000:4000"
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3000:3000"
